# Generated by Django 4.1.8 on 2023-04-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_Model',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_mob_no', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('prd_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('Product_brand', models.CharField(max_length=30)),
                ('Product_category', models.CharField(max_length=30)),
                ('product_cost', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='static/media')),
                ('product_releasedate', models.DateField()),
                ('product_description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_id', models.CharField(max_length=30)),
                ('company_business_name', models.CharField(max_length=30)),
                ('Seller_name', models.CharField(max_length=30)),
                ('Seller_mob_no', models.BigIntegerField()),
                ('Seller_email', models.EmailField(max_length=254)),
                ('Seller_address', models.CharField(max_length=60)),
            ],
        ),
    ]
