# Generated by Django 4.1.8 on 2023-04-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('Product_brand', models.CharField(max_length=30)),
                ('Product_category', models.CharField(max_length=30)),
                ('product_cost', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='static/media')),
                ('product_releasedate', models.DateField()),
                ('product_description', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Model',
        ),
    ]
