# Generated by Django 4.1.8 on 2023-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart_model_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_mob_no', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Buyer_Model',
        ),
    ]
