# Generated by Django 4.1.8 on 2023-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_model_delete_buyer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('user_name', models.CharField(max_length=30)),
                ('user_mob_no', models.BigIntegerField()),
                ('alternate_No', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_address', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='User_model',
        ),
    ]
