# Generated by Django 4.1.8 on 2023-04-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_user_mode_delete_usermode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("product_cost", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Customer1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="order_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(default=True)),
                ("Product_name", models.CharField(max_length=250)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("Qty", models.PositiveIntegerField(default=1)),
                ("price", models.IntegerField()),
                ("ordered_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Accepted", "Accepted"),
                            ("Packed", "Packed"),
                            ("On the Way", "On The Way"),
                            ("Delivered", "Delivered"),
                            ("Cancel", "Cancel"),
                        ],
                        default="pendding",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=30)),
                ("Product_brand", models.CharField(max_length=30)),
                ("Product_category", models.CharField(max_length=30)),
                ("product_cost", models.IntegerField()),
                ("product_image", models.ImageField(upload_to="static/media")),
                ("product_releasedate", models.DateField()),
                ("product_description", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Usermode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
                ("user_mob_no", models.BigIntegerField()),
                ("alternate_No", models.BigIntegerField()),
                ("user_email", models.EmailField(max_length=254)),
                ("user_address", models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name="cart_model",
            name="Product_brand",
        ),
        migrations.DeleteModel(
            name="User_mode",
        ),
        migrations.DeleteModel(
            name="Cart_model",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="cart1",
            name="Product_brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.product1"
            ),
        ),
    ]
