# Generated by Django 4.1.8 on 2023-04-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_cart1_customer1_order_details_product1_usermode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product1",
            name="prod_quantity",
            field=models.IntegerField(default=1),
        ),
    ]
