# Generated by Django 4.1.8 on 2023-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_product1_prod_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product1",
            name="Seller_mob_no",
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product1",
            name="product_image",
            field=models.ImageField(upload_to="static/media/"),
        ),
    ]
