# Generated by Django 4.1.8 on 2023-04-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_product1_seller_mob_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product1",
            name="Seller_mob_no",
            field=models.BigIntegerField(default=1),
        ),
    ]
