# Generated by Django 4.1.8 on 2023-04-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_product1_seller_mob_no"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product1",
            new_name="Product_details",
        ),
    ]
