# Generated by Django 4.1.8 on 2023-04-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_rename_product1_product_details"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart1",
        ),
        migrations.DeleteModel(
            name="Product_details",
        ),
    ]
