# Generated by Django 4.1.8 on 2023-04-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_delete_cart1_delete_product_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=30)),
                ("Product_brand", models.CharField(max_length=30)),
                ("Product_category", models.CharField(max_length=30)),
                ("product_cost", models.IntegerField()),
                ("prod_quantity", models.IntegerField(default=1)),
                ("product_image", models.ImageField(upload_to="static/media/")),
                ("product_releasedate", models.DateField()),
                ("product_description", models.CharField(max_length=60)),
                ("Seller_mob_no", models.BigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Cart1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=10)),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("product_cost", models.IntegerField(default=0)),
                (
                    "Product_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.product_details",
                    ),
                ),
            ],
        ),
    ]
