# Generated by Django 4.1.8 on 2023-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_sales_details_user_details_delete_customer1"),
    ]

    operations = [
        migrations.CreateModel(
            name="sales_detailss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField()),
                ("seller_id", models.IntegerField()),
                ("buyer_id", models.IntegerField()),
                ("product_id", models.IntegerField()),
                ("prd_quant", models.IntegerField()),
                ("total_cost", models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="sales_details",
        ),
    ]
