# Generated by Django 4.1.8 on 2023-04-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_sales_detailss_delete_sales_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_details",
            name="address",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="user_details",
            name="dob",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="user_details",
            name="email_id",
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
