# Generated by Django 4.1.8 on 2023-04-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_user_details_address_user_details_dob_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user_details",
            new_name="User_Model",
        ),
    ]
