# Generated by Django 4.1.8 on 2023-04-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_user_details_delete_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=10)),
                ("email_id", models.EmailField(default=None, max_length=254)),
                ("address_field", models.CharField(default=None, max_length=50)),
                ("dob", models.DateField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name="user_details",
        ),
    ]
