# Generated by Django 4.1.8 on 2023-04-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_user_model_delete_user_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_model",
            name="address_field",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user_model",
            name="dob",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="user_model",
            name="email_id",
            field=models.EmailField(max_length=254),
        ),
    ]
