# Generated by Django 4.1.8 on 2023-04-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_alter_user_model_address_field_alter_user_model_dob_and_more"),
    ]

    
