# Generated by Django 4.1.8 on 2023-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_sales_detailss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales_detailss",
            name="buyer_id",
            field=models.BigIntegerField(),
        ),
    ]
